// `chakra init`: scaffold chakra.config.js from the routes an Express or Fastify app declares.
//
// Route discovery is a static scan of source files, so it never runs application code.
// Priorities are guesses from the path and method; the developer reviews the file.

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Priority } from '../types';

export type Framework = 'express' | 'fastify';

export interface InitOptions {
  /** Project directory. Default `process.cwd()`. */
  readonly dir?: string;
  /** Overwrite an existing config file. */
  readonly force?: boolean;
  /** Framework, when it cannot be read from package.json. Default `express`. */
  readonly framework?: Framework;
}

export interface InitResult {
  readonly file: string;
  readonly framework: Framework;
  readonly routes: Readonly<Record<string, Priority>>;
  /** The code to add to the app. */
  readonly snippet: string;
}

const SKIP_DIRS = new Set(['node_modules', 'dist', 'build', 'coverage', '.git', '.next', 'out']);
const SOURCE = /\.(?:[cm]?js|[cm]?ts)$/;
const ROUTE = /\b\w+\.(get|post|put|patch|delete)\(\s*(['"`])(\/[^'"`\s$]*)\2/gi;
const CRITICAL =
  /checkout|payment|\/pay\b|billing|order|login|logout|sign-?in|sign-?up|auth|token|health|ready|live/i;
const SHEDDABLE =
  /recommend|suggest|related|trending|popular|analytics|track|telemetry|report|export|feed|preview/i;
const MAX_FILES = 2000;
const MAX_BYTES = 512 * 1024;

/** Guess a route's priority from its method and path. */
export function guessPriority(method: string, path: string): Priority {
  if (CRITICAL.test(path)) return 'critical';
  if (SHEDDABLE.test(path)) return 'sheddable';
  return method === 'GET' ? 'normal' : 'high';
}

/** Find `x.get('/path', ...)`-style route declarations under `dir`, keyed `'METHOD /path'`. */
export function scanRoutes(dir: string): Record<string, Priority> {
  const routes: Record<string, Priority> = {};
  let files = 0;
  const walk = (d: string): void => {
    for (const name of readdirSync(d)) {
      if (files >= MAX_FILES || SKIP_DIRS.has(name) || name.startsWith('.')) continue;
      const p = join(d, name);
      const st = statSync(p);
      if (st.isDirectory()) walk(p);
      else if (SOURCE.test(name) && !name.endsWith('.d.ts') && st.size <= MAX_BYTES) {
        files++;
        for (const [, m, , path] of readFileSync(p, 'utf8').matchAll(ROUTE)) {
          const method = m.toUpperCase();
          routes[`${method} ${path}`] = guessPriority(method, path);
        }
      }
    }
  };
  walk(dir);
  return Object.fromEntries(Object.entries(routes).sort(([a], [b]) => a.localeCompare(b)));
}

/** Render chakra.config.js. `esm` writes `export default` instead of `module.exports`. */
export function renderConfig(routes: Readonly<Record<string, Priority>>, esm = false): string {
  const entries = Object.entries(routes);
  const body = entries.length
    ? entries.map(([k, p]) => `    '${k}': '${p}',`).join('\n')
    : "    // 'POST /checkout': 'critical',\n    // 'GET /recommendations': 'sheddable',";
  return `// CHAKRA route priorities: critical | high | normal | sheddable (lowest is shed first).
// Generated by \`npx chakra init\` from the routes found in this project. Review before use.
// Unlisted routes use defaultPriority. Patterns support :param and a trailing *.
/** @type {import('chakra-middleware').ChakraOptions} */
${esm ? 'export default' : 'module.exports ='} {
  defaultPriority: 'normal',
  routes: {
${body}
  },
};
`;
}

/** The lines to add to the app, right after it is created. */
export function setupSnippet(framework: Framework, esm = false): string {
  const load = esm
    ? "import { chakra } from 'chakra-middleware';\nimport config from './chakra.config.js';\nconst c = chakra(config);"
    : "const { chakra } = require('chakra-middleware');\nconst c = chakra(require('./chakra.config'));";
  const mount = framework === 'fastify' ? 'app.register(c.fastify);' : 'app.use(c);';
  return `${load}\n${mount}\napp.get('/metrics', c.metricsHandler); // optional Prometheus endpoint`;
}

/** Write chakra.config.js into `dir`. Throws if it exists and `force` is not set. */
export function runInit(options: InitOptions = {}): InitResult {
  const dir = options.dir ?? process.cwd();
  const file = join(dir, 'chakra.config.js');
  if (existsSync(file) && !options.force)
    throw new Error(`${file} already exists (use --force to overwrite)`);
  const pkg = readPackage(dir);
  const deps = { ...pkg.dependencies, ...pkg.devDependencies };
  const framework = options.framework ?? (deps.fastify && !deps.express ? 'fastify' : 'express');
  const esm = pkg.type === 'module';
  const routes = scanRoutes(dir);
  writeFileSync(file, renderConfig(routes, esm));
  return { file, framework, routes, snippet: setupSnippet(framework, esm) };
}

interface PackageJson {
  type?: string;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

function readPackage(dir: string): PackageJson {
  try {
    return JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as PackageJson;
  } catch {
    return {};
  }
}
