'use strict';
// Runs every benchmark and writes bench/results.json and bench/RESULTS.md.
//   npm run bench                        # from the repository root (builds first)
//   BENCH_ONLY=micro,overhead npm run bench

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync, execSync } = require('node:child_process');

const ONLY = (process.env.BENCH_ONLY || 'micro,overhead,overload').split(',');
const MICRO_FLAGS = ['--expose-gc', '--min-semi-space-size=64'];

function sh(cmd) {
  try {
    return execSync(cmd, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return 'unknown';
  }
}

function machine() {
  const pkg = (name) => require(`${name}/package.json`).version;
  return {
    date: new Date().toISOString(),
    cpu: `${os.cpus()[0].model} × ${os.availableParallelism()}`,
    memoryGb: Math.round(os.totalmem() / 2 ** 30),
    os: `${os.type()} ${os.release()} ${os.arch()}`,
    node: process.version,
    commit: sh('git rev-parse --short HEAD'),
    versions: { express: pkg('express'), fastify: pkg('fastify'), autocannon: pkg('autocannon') },
  };
}

// The microbenchmark needs V8 flags, so it runs in its own process.
function micro() {
  const out = execFileSync(process.execPath, [...MICRO_FLAGS, path.join(__dirname, 'micro.js')], {
    env: { ...process.env, BENCH_JSON: '1' },
    encoding: 'utf8',
  });
  return JSON.parse(out.trim().split('\n').at(-1));
}

const table = (headers, rows) =>
  [
    `| ${headers.join(' | ')} |`,
    `|${headers.map(() => '---').join('|')}|`,
    ...rows.map((r) => `| ${r.join(' | ')} |`),
  ].join('\n');
const ms = (x) => (x === null || x === undefined ? 'n/a' : `${x} ms`);

function markdown(r) {
  const m = r.machine;
  const out = [
    '# CHAKRA benchmark results',
    '',
    `Generated by \`npm run bench\` on ${m.date} at commit \`${m.commit}\`. Re-run it to reproduce; see [README](README.md) for method.`,
    '',
    `**Machine:** ${m.cpu}, ${m.memoryGb} GB RAM, ${m.os}, Node ${m.node}. ` +
      `express ${m.versions.express}, fastify ${m.versions.fastify}, autocannon ${m.versions.autocannon}.`,
    '',
  ];
  if (r.micro) {
    out.push(
      '## Admission path per request',
      '',
      `\`node ${MICRO_FLAGS.join(' ')} bench/micro.js\`, ${r.micro.iterations.toLocaleString('en')} iterations × ${r.micro.runs} runs, median. Limiter: ${r.micro.limiter}.`,
      '',
      table(
        ['Path', 'ns/request (median)', 'ns/request (best)', 'heap bytes/request'],
        r.micro.results.map((x) => [x.name, x.nsPerOp, x.nsMin, x.bytesPerOp]),
      ),
      '',
    );
  }
  if (r.overhead) {
    const o = r.overhead;
    const rows = (list, withShed) =>
      list.map((x) => [
        x.framework,
        x.protection === 'none' ? 'off' : 'on',
        x.rps.toLocaleString('en'),
        x.rpsDelta || '—',
        ms(x.p50),
        ms(x.p99),
        ...(withShed ? [`${x.shedPct}%`] : []),
      ]);
    const head = ['Framework', 'CHAKRA', 'req/s', 'Δ req/s', 'p50', 'p99'];
    out.push(
      '## Middleware overhead',
      '',
      `\`node bench/overhead.js\`: autocannon, ${o.connections} connections, \`GET /hello\` returning a small JSON body, ${o.duration} s per run after a 3 s warm-up, median of ${o.rounds} interleaved rounds. autocannon reports latency in whole milliseconds.`,
      '',
      '**Maximum throughput.** Closed loop at saturation. CHAKRA runs in dry-run mode so it does its full per-request work (decide, limiter, metrics) but admits everything.',
      '',
      table(head, rows(o.max, false)),
      '',
      `**Normal load.** Paced at ${o.loadShare * 100}% of the raw framework's maximum (${Object.entries(
        o.rates,
      )
        .map(([f, n]) => `${f} ${n.toLocaleString('en')} req/s`)
        .join(', ')}), CHAKRA enforcing.`,
      '',
      table([...head, 'shed'], rows(o.load, true)),
      '',
    );
  }
  if (r.overload) {
    const o = r.overload;
    const spike = o.phases.find((p) => p.name === 'spike');
    const base = o.phases.find((p) => p.name === 'baseline');
    out.push(
      '## Overload: critical traffic during a spike',
      '',
      `\`node bench/overload.js\`: ${o.framework} demo shop with a simulated database of ${o.capacity.pool} connections × ${o.capacity.serviceMs} ms ` +
        `plus ${o.capacity.cpuUs} µs CPU per request (about ${o.capacity.rps} req/s for this mix). ` +
        `Open-loop load: ${base.rps} req/s, then a ${spike.seconds} s spike at ${spike.rps} req/s, then back to ${base.rps} req/s. ` +
        `Mix: ${o.mix.map((x) => `${Math.round(x.weight * 100)}% \`${x.method} ${x.path}\` (${x.priority})`).join(', ')}. ` +
        `Client timeout ${o.timeoutMs} ms counts as a failure. Fixed cap: ${o.capacity.fixedCap} in flight, 503 above it.`,
      '',
      'Figures are for requests sent during the spike.',
      '',
      table(
        [
          'Protection',
          'critical success',
          'critical p50',
          'critical p99',
          'normal success',
          'sheddable success',
          'goodput (2xx/s)',
          'first 503 after spike',
          `critical healthy after (≥ 99% ok, p99 ≤ ${o.sloMs} ms)`,
        ],
        o.results.map((x) => [
          x.mode === 'none'
            ? 'none'
            : x.mode === 'cap'
              ? `fixed cap (${o.capacity.fixedCap})`
              : 'CHAKRA',
          `${x.criticalSuccess}%`,
          ms(x.criticalP50),
          ms(x.criticalP99),
          `${x.normalSuccess}%`,
          `${x.sheddableSuccess}%`,
          x.goodputRps,
          x.firstShedMs === null ? 'never' : ms(x.firstShedMs),
          x.recoveredMs === null ? 'never' : ms(x.recoveredMs),
        ]),
      ),
      '',
      `Critical p99 before the spike: ${o.results.map((x) => `${x.mode} ${ms(x.criticalBaselineP99)}`).join(', ')}.`,
      '',
    );
  }
  return out.join('\n');
}

async function main() {
  // A partial run (BENCH_ONLY) keeps the other sections from the last results.json.
  const file = path.join(__dirname, 'results.json');
  const previous = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : {};
  const results = { ...previous, machine: machine() };
  if (ONLY.includes('micro')) results.micro = micro();
  if (ONLY.includes('overhead')) results.overhead = await require('./overhead').main();
  if (ONLY.includes('overload')) results.overload = await require('./overload').main();
  fs.writeFileSync(file, JSON.stringify(results, null, 2) + '\n');
  fs.writeFileSync(path.join(__dirname, 'RESULTS.md'), markdown(results));
  console.log(markdown(results));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
